#if STOWKIT_LIVE_VERIFICATION
import Foundation
import CryptoKit
import AppKit

/// Explicitly compiled validation runner. Never reads or enables the user's active archive.
@MainActor enum CloudLiveVerification {
    static func run() async {
        let root = DocumentStorageManager.defaultRoot.appendingPathComponent("CloudValidation/\(UUID())")
        var report: [String] = []
        func record(_ message: String) {
            report.append(message)
            print("STOWKIT_LIVE: \(message)")
            try? FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
            try? report.joined(separator: "\n").write(to: root.appendingPathComponent("report.txt"), atomically: true, encoding: .utf8)
        }
        func require(_ condition: Bool, _ message: String) throws {
            guard condition else { throw NSError(domain: "StowKitValidation", code: 1, userInfo: [NSLocalizedDescriptionKey: message]) }
        }
        record("START \(root.path)")
        do {
            #if STOWKIT_PRODUCTION_VERIFICATION
            guard CloudSetup.environment == "Production" else { throw CloudArchiveError.setupRequired }
            #else
            guard CloudSetup.environment == "Development" else { throw CloudArchiveError.setupRequired }
            #endif
            let a = try ArchiveRepository(root: root.appendingPathComponent("A"))
            let binding = try await CloudSetup.privateBinding(archiveID: a.archiveID)
            let transport = CloudKitArchiveTransport(binding: binding)
            try await transport.verifyAccount()
            record("PASS \(CloudSetup.environment) account and isolated zone \(binding.zoneName)")
            let storageA = DocumentStorageManager(root: root.appendingPathComponent("A"))
            try await storageA.prepare()
            // Generated bytes exceed one chunk. No private document is read or uploaded.
            let bytes = Data(repeating: 0x53, count: OriginalManifest.chunkSize + 137)
            let hash = SHA256.hash(data: bytes).map { String(format: "%02x", $0) }.joined()
            let id = UUID(), date = Date()
            let doc = HouseholdDocument(id: id, archiveID: a.archiveID, title: "Fictional cloud verification",
                originalFilename: "fictional-transfer.pdf", documentDate: date, importedAt: date, modifiedAt: date,
                contentType: "com.adobe.pdf", contentHash: hash, fileSize: Int64(bytes.count), relativePath: "Originals/\(id.uuidString.prefix(2))/\(id).pdf")
            let source = try storageA.originalURL(for: doc.relativePath)
            try FileManager.default.createDirectory(at: source.deletingLastPathComponent(), withIntermediateDirectories: true)
            try bytes.write(to: source)
            try a.insert(doc)
            _ = try a.setPageCount(id, count: 1)
            _ = try a.savePage(id, index: 0, result: .init(text: "Fictional cloud verification zebra", method: .embedded))
            _ = try a.setProcessingState(id, .complete)
            var syncFailure: String?
            func coordinator(_ repository: ArchiveRepository, _ storage: DocumentStorageManager) async throws -> (CloudSyncCoordinator, TextSearchService) {
                let container = repository.container
                let reader = await Task.detached { TextSearchService(modelContainer: container) }.value
                try await reader.configure(root: storage.root, archiveID: repository.archiveID)
                return (CloudSyncCoordinator(repository: repository, storage: storage, reader: reader, transport: transport,
                    onStatus: { status, failed in record(status); if failed { syncFailure = status } }, onUpdate: {}), reader)
            }
            let (ca, _) = try await coordinator(a, storageA)
            ca.schedule(); await ca.waitUntilIdle()
            try require(syncFailure == nil, syncFailure ?? "Upload failed")
            try require(try a.pendingSyncOperations().isEmpty, "Metadata remains pending")
            try require(try a.originalCloudState(id)?.cloudVerified == true, "Original not verified")
            record("PASS multi-chunk original upload and independent hash verification")
            let b = try ArchiveRepository(root: root.appendingPathComponent("B"), joiningArchiveID: a.archiveID)
            let storageB = DocumentStorageManager(root: root.appendingPathComponent("B"))
            try await storageB.prepare(); await storageB.setCloudTransport(transport)
            let (cb, readerB) = try await coordinator(b, storageB)
            cb.schedule(); await cb.waitUntilIdle()
            try require(syncFailure == nil, syncFailure ?? "Catch-up failed")
            guard var received = try b.matching(hash: hash) else { throw CloudArchiveError.missingResult }
            try require(!FileManager.default.fileExists(atPath: try storageB.originalURL(for: received.relativePath).path), "Catch-up downloaded original")
            let hits = try await readerB.search("verification zebra", destination: .recent, newestFirst: true)
            try require(hits.total == 1, "Received text is not searchable")
            record("PASS second local store receives searchable text without materializing original")
            let downloaded = try await storageB.localOriginal(for: received)
            try require(try Data(contentsOf: downloaded) == bytes, "Explicit download mismatch")
            record("PASS explicit original download is byte-identical")
            received.summary = "Fictional second-store update"
            try b.update(received); cb.schedule(); await cb.waitUntilIdle()
            ca.schedule(); await ca.waitUntilIdle()
            try require(syncFailure == nil, syncFailure ?? "Edit sync failed")
            try require(try a.document(id)?.summary == received.summary, "Cross-store update did not converge")
            record("PASS second-store edit converges through live CloudKit")
            await ca.stop(); await cb.stop()
            record("SUCCESS private-cloud smoke test; two-account household sharing remains unverified")
        } catch { record("FAIL \(error.localizedDescription)") }
        NSApplication.shared.terminate(nil)
    }
}
#endif
